language: php
php:
- '5.6'
script: echo "We don't have tests yet :("
before_deploy:
- sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key: $GITHUB_TOKEN
  file: plugin-prestashop-webpay-rest-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-prestashop-webpay-rest
    tags: true
