language: php
php:
- '5.6'
script: echo "We don't have tests yet :("
before_deploy:
- sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: WLQXkVm4dZoG8iPgOa/Y98x5CFvgIyooEJQkmC3ZrnEfIUvlMF8KAvie3JPawYvIpqvF0W9AnDBBrkClgZzS2FPGjDqHwjAYlHpwmHMeRLvtcgJ06yKvYFfU2aNvTp76VeiwhiTdKxYrmwh0rdBgel3DmQmdY9H8q3hPUHKnlS0T5KXLgpaj6/DnT3w/Gq+bk+x4uefyGAGc4H16p2gAjBBKxZwZs1D/xMTmJCGohSPP+LmguOeQAyGsm5voKYbdBQEKcGNG99wsGufrLAp071fDyzX8+1OX/oZEsb8xnN2ENJ9J8viKkJW1L4dv6IHT2esq6dKsGrB9aiGAOX2U993+r9/6gs8L1mbdcLX0WmkEec7a1gq0f5CKp6uMsmPR8viO8SOUQzdRQbJS6BK2kVezcEX4hR0WJrgISR9wLelUv3AIPXamm56LhQDtqlIad1rJ7o+VCVCvUug68XqySDOLS2HE6WXvQEErdrtTYSwFRGuDRtpvAy2JP7jecIRAh7z0GOpF/ZX4U+qoNaGx0umlXj4LHYuYO7Pa50ODEEOxgOE57u2Z7WHCb8moYdUgHL38Icr9CzEn9WVjulxC+w1yxsChLIHLpnDOUJOoHeCzVJAChE5RgHW7UulKD5pLhODooZ5Ryaf7bq4uklGw3OiSXGUvkjx8MuvykpomKIg=
  file: plugin-prestashop-webpay-rest-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-prestashop-webpay-rest
    tags: true
env:
  global:
    secure: tjwqk53pw8+dHA4ZvSeymEBr2mJKm4fooQhbOmUr13YZ/zUZ85aJpLVxdNatuQsbkyDiElyNrCjXe6VHceNtNcNO+NVNHtwdowHi6wKKTrrKxA6Yah0uqNs9kAM2f5fBHzNCz4/DvDZZDCioGpEQvIGEC6g3UbvDUFIib6Nh7i9Qkn/OGOMhEwE8rrLCRZAciZYR162MjCH0Ge9avV8DEvyZZurPfAa5P+56hfC8+W1UYZw4e/XgicXRQpDZXMXj8o+5XYiJdnAqJAzOniEf6B2u/hU/b3GRQQZL8N5MISX2ynOprxNZBopWd4vmhP/vKatVyl9jJfBfcZL9+3cpKMsE9dq9iu/tBYbGP8asi2cfYThBQMC6wjwN8KjMmYAp6Y9sFFhifVUWzFTpLxNyQUMFU+lKU3oHaM5/6ati987/d1jvrHvks19bQ0Xu8DPsDI69wAedLJ96amrCqgQPJeMEArLDPlgawVCH+Zx8zxh+oe3XG2+YGoaroAEE93iwviJN6L9pDRTkokGl7PpOVLie3iJi+8HEHre3hsR1tFlTdgs47dQUCCjBLqueFH5gTNzPiB/eJ02xV7djOn2LljuBtBf+OMLzUOX7DW90acROXrnlJ6H6eYk7CrfzI7VpwSd8qw162RS6hUL5E+r6hcg0CbO9FLSm6svN+PTurCk=
