language: php
php:
  - '5.6'

script: echo "We don't have tests yet :("

before_deploy:
  - sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: WLQXkVm4dZoG8iPgOa/Y98x5CFvgIyooEJQkmC3ZrnEfIUvlMF8KAvie3JPawYvIpqvF0W9AnDBBrkClgZzS2FPGjDqHwjAYlHpwmHMeRLvtcgJ06yKvYFfU2aNvTp76VeiwhiTdKxYrmwh0rdBgel3DmQmdY9H8q3hPUHKnlS0T5KXLgpaj6/DnT3w/Gq+bk+x4uefyGAGc4H16p2gAjBBKxZwZs1D/xMTmJCGohSPP+LmguOeQAyGsm5voKYbdBQEKcGNG99wsGufrLAp071fDyzX8+1OX/oZEsb8xnN2ENJ9J8viKkJW1L4dv6IHT2esq6dKsGrB9aiGAOX2U993+r9/6gs8L1mbdcLX0WmkEec7a1gq0f5CKp6uMsmPR8viO8SOUQzdRQbJS6BK2kVezcEX4hR0WJrgISR9wLelUv3AIPXamm56LhQDtqlIad1rJ7o+VCVCvUug68XqySDOLS2HE6WXvQEErdrtTYSwFRGuDRtpvAy2JP7jecIRAh7z0GOpF/ZX4U+qoNaGx0umlXj4LHYuYO7Pa50ODEEOxgOE57u2Z7WHCb8moYdUgHL38Icr9CzEn9WVjulxC+w1yxsChLIHLpnDOUJOoHeCzVJAChE5RgHW7UulKD5pLhODooZ5Ryaf7bq4uklGw3OiSXGUvkjx8MuvykpomKIg=
  file: "plugin-prestashop-webpay-rest-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-prestashop-webpay-rest
    tags: true
