ps_controller_configure:   
    path: /webpay/configure/admin
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\WebpayPlus\Controller\Admin\ConfigureController::configure'
        _legacy_controller: 'WebpayPlusConfigure'
        _legacy_link: 'WebpayPlusConfigure'

# tbk plugin api
ps_controller_plugin_execute:
    path: /webpay/plugin/execute
    controller: PrestaShop\Module\WebpayPlus\Controller\Admin\TbkPluginController::execute
    methods: [POST]
