services:
  db:
    image: mariadb:10.11
    container_name: prestashop-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop123
    command: >
      --default-time-zone='America/Santiago'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pprestashop123"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - net
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestashop-dev-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PS_LANGUAGE=es
      - PS_INSTALL_AUTO=1
      - PS_INSTALL_DB=1
      - PS_ERASE_DB=1
      - PS_DEV_MODE=1
      - PS_DOMAIN=localhost:8080
      - ADMIN_MAIL=admin@admin.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=adminop
      - PS_FOLDER_INSTALL=installop
      - PS_COUNTRY=cl
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop123
    volumes:
      - ../webpay:/var/www/html/modules/webpay:cached
      - ../:/workspace:cached
      - ./container/log:/var/log
      - ./container/log/php:/var/log/php
      - ./container/log/php/php_runtime:/var/www/html/var/log
      - ./container/log/prestashop:/var/www/html/var/logs
      - ./install-module.sh:/tmp/init-scripts/install-module.sh:ro
    expose:
      - "9000"
    networks:
      - net

  nginx:
    image: nginx:1.27-alpine
    container_name: prestashop-dev-nginx
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ../webpay:/var/www/html/modules/webpay:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./container/log/nginx:/var/log/nginx
    networks:
      - net

networks:
  net:
