version: '3'
services:
  web:
    image: "prestashop/prestashop:1.7.8.6-7.4-apache"
    container_name: "php7.4-pres1.7.8.6-apache_prestashop"
    environment:
      - PS_LANGUAGE=es
      - PS_INSTALL_AUTO=1
      - PS_INSTALL_DB=1
      - PS_ERASE_DB=1
      - PS_DEV_MODE=1
      - PS_DOMAIN=localhost:8080
      - ADMIN_MAIL=admin@admin.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=adminop
      - PS_FOLDER_INSTALL=installop
      - PS_COUNTRY=cl
      - DB_NAME=prestashop
      - DB_SERVER=php7.4-pres1.7.8.6-apache_mariadb
    volumes:
      - ./modules:/var/www/html/modules  
      - ./log:/var/log
    ports:
      - "8080:80"
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.7.8
    container_name: php7.4-pres1.7.8.6-apache_mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=admin

