version: '3'
services:
  web:
    image: "prestashop/prestashop:8.2.0-8.1-apache"
    container_name: "php8.1-pres8.2.0-apache_prestashop"
    environment:
      - PS_LANGUAGE=es
      - PS_INSTALL_AUTO=1
      - PS_INSTALL_DB=1
      - PS_ERASE_DB=1
      - PS_DEV_MODE=1
      - PS_DOMAIN=localhost:8080
      - ADMIN_MAIL=admin@admin.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=adminop
      - PS_FOLDER_INSTALL=installop
      - PS_COUNTRY=cl
      - DB_NAME=prestashop
      - DB_SERVER=php8.1-pres8.2.0-apache_mariadb
    volumes:
      - ./log:/var/log
      - type: bind
        source: ../../webpay
        target: /var/www/html/modules/webpay
      - ../install-module.sh:/tmp/init-scripts/install-module.sh:ro
    ports:
      - "8080:80"
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.7.8
    container_name: php8.1-pres8.2.0-apache_mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=admin

