name: Prestashop upload binaries to release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build the plugin with PHP 8.2 and upload binaries
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: 2. Setup php and composer
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: "8.2"

      - name: 3. Package plugin
        id: package
        run: |
          chmod +x package.sh
          ./package.sh

      - name: 4. Upload binaries to release
        shell: bash
        run: |
          gh release upload "$RELEASE_TAG" \
            "${{ steps.package.outputs.package_output }}" \
            --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
